name: The Black Cat
description: blog about MSIL-related topics and obfuscation
meta_description: "The Black Cat, blog about MSIL-related topics and obfuscation"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "http://xenocoderce.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Sam Harwood"

# Disqus config
disqus-shortname: ""
